import nltk, re

from nltk import word_tokenize, pos_tag
from nltk.corpus import stopwords
from nltk.corpus.reader.wordnet import ADJ, ADV, NOUN, VERB
from nltk.stem import WordNetLemmatizer

nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

def convert_pos_tag(tag):
    """
    Convert a POS tag from the Penn tagset to the WordNet tagset.

    Takes a tag generated by NLTK.
    Returns a tag from the WordNet tagset or None if no corresponding tag could be found.
    """
    # Source: https://www.programcreek.com/python/example/91610/nltk.corpus.wordnet.NOUN
    if tag in ['JJ', 'JJR', 'JJS']:
        return ADJ
    elif tag in ['RB', 'RBR', 'RBS']:
        return ADV
    elif tag in ['NN', 'NNS', 'NNP', 'NNPS']:
        return NOUN
    elif tag in ['VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ']:
        return VERB
    return NOUN

def tokenize(text):
    """
    Tokenizer function that removes stopwords, lowers case, tags part of speech, and lemmatizes.

    Takes a text string.
    Returns fully tokenized and normalized words.
    """
    tokens = word_tokenize(text)
    words = [token for token in tokens if re.match("[a-zA-Z0-9]", token)]
    no_stopwords = [word for word in words if word not in stopwords.words("english")]
    lowercase_words = [word.lower() for word in no_stopwords]
    pos_tagged_words = pos_tag(lowercase_words)
    lemmatized_words = [WordNetLemmatizer().lemmatize(word, pos=convert_pos_tag(pos)) for word, pos in pos_tagged_words]
    return lemmatized_words

from disaster_app import app

app.run(host='localhost', port=3001, debug=True)